### ISSUE TITLE
Retry interval parameter timings ignored

### ISSUE THREAD

**Issue by PauliusP17** [novacode-nl/odoo-celery#14]
The `interval_start`, `interval_step` and `interval_max` parameters seem to be completely ignored. This is how I create the celery task:
```                
self.env["celery.task"].call_task("res.partner", "my_custom_method", partner_id=self.id, mode='updated', type='Customer', celery=celery)
```
And these are the "celery" parameters I pass:

```
celery = {
            'countdown': 2,
            'retry': True,
            'retry_policy': {
                'max_retries': 4,
                'interval_start': 120,
                'interval_step': 60,
                'interval_max': 300,
            }
        }
```
Also tried it this way:
```
celery = {
            'countdown': 2,
            'retry': True,
            'max_retries': 4,
            'interval_start': 120,
            'interval_step': 60,
            'interval_max': 300,
        }
```

The task does indeed start after 2 seconds and is retried 4 times, but instead of waiting for 120 seconds, the task retries instantly every time and goes into the Failed state after the 4 tries.

**Comment by bobslee** [comment]
I can confirm this was an issue - it didn't worked like expected/documented by me.

IMHO the Celery documentation was a bit shady to me. However I found an extensive article about [ How to Retry Failed Tasks in Celery ](https://coderbook.com/@marcus/how-to-automatically-retry-failed-tasks-with-celery/).

There are 2 things that could go wrong with tasks:
1. Connection to broker issues. The retry is configured by the `retry_policy` param.
2. Exceptions raised by code running in the worker (this fix).

In this case this reported issue is about the second (2) one.
The **retry interval** which makes the timing, is set by either:
- `countdown`
- `eta` (not yet supported by this module).

I implemented a fix into the Odoo worker. So already implemented `call_task()` invocations and params, should work and don't need any changes.

See the **Celery Example** module for the [task_with_error](https://github.com/novacode-nl/odoo-celery/blob/12.0/celery_example/models/celery_example.py#L21) which sets the **retry interval** by the `countdown` param.

For example:
```
celery = {
    'countdown': 10, 'retry': True,
    'retry_policy': {'max_retries': 2, 'interval_start': 2}
}
```
