### ISSUE TITLE
Cron to create new Queue records (requires PR #20)

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-celery#23]
After merging PR #20 it would be nice to implement a (daily) Cron which creates new Queue records.
Leave existing but inactive Queue records, because that's a viable case/usage.

**Comment by antonioburic** [comment]
Added with the PR #20 ^^

378f218

**Comment by bobslee** [comment]
Awesome and thanks @antonioburic !
Works like a charm :)
