### ISSUE TITLE
[13.0, 14.0] Scheduled task - UNKNOWN ERROR FROM call_task: Datetime field expects a naive  datetime

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-celery#33]
Error upon executing/creating a Scheduled Task.

```
ERROR [DB_NAME] odoo.addons.celery.models.celery_task: UNKNOWN ERROR FROM call_task: Datetime field expects a naive datetime: 2020-12-18 09:00:00.757320+00:00 
```

**Comment by revskill10** [comment]
Any ETA for the fix ?

**Comment by antonioburic** [comment]
I will have a look/fix this one later this week.

**Comment by bobslee** [comment]
Thanks @antonioburic !
Just a heads up... you could use the `celery_example` module to test.

**Comment by antonioburic** [comment]
Thanks @bobslee  - PR with a fix created, this should be it. Please check/merge when convenient. ^^

**Comment by bobslee** [comment]
Thanks for the PR @antonioburic !

I also looked to the "Celery Task Settings" UI.
Maybe we should add some info on the form-view, regarding the **hours (float)** fields and the UTC datetime ?
