### ISSUE TITLE
Odoo.sh usage instructions

### ISSUE THREAD

**Issue by diegospire** [novacode-nl/odoo-celery#35]
I need certain information about putting this module on odoo.sh, I know
how to add custom options on odoo.conf.  Documentation also metion 
something about run odoo.py file.  How can I do that on odoo.sh?

**Comment by bobslee** [comment]
Hi @diegospire , I never used odoo.sh. Is there shell/SSH access possible?
You'll also need to install a MQ broker e.g. RabbitMR (preferred), Redis.

**Comment by diegospire** [comment]
Hi @bobslee, thanks for the fast feedback, on Odoo.sh you can install python packages using
requirements.txt file on your module.  There is no possible to install software dependencies via
a package manager.  (https://www.odoo.sh/faq#install_dependencies)

**Comment by bobslee** [comment]
I just shortly read the odoo.sh docs. Seems there's no way to get the Celery module working on odoo.sh.
Maybe the OCA `queue_job` module could be used? https://github.com/OCA/queue/

**Comment by diegospire** [comment]
Yes I saw it, I like the celery approach, for that reason I was wondering if odoo-celery can be used on Odoo.sh.
I will review queue module, thanks for your time!!!

**Comment by bobslee** [comment]
Please close this issue if satisfied :-)
