### ISSUE TITLE
How to configure the broker URL?

### ISSUE THREAD

**Issue by oadiazp** [novacode-nl/odoo-celery#39]
Hi:

I'm looking inside of your code and I can't see the way I can pass the BROKER_URL and in your example isn't clear.
How do you recommend to do it?

Regards
Omar

**Comment by bobslee** [comment]
Hi @oadiazp Please explain more detailed.
Some reference to code please.

**Comment by ruter** [comment]
Hi @bobslee 

As celery documentation [mention](https://docs.celeryproject.org/en/stable/getting-started/first-steps-with-celery.html#application), there is the broker keyword argument, specifying the URL of the message broker you want to use.

```python
app = Celery('tasks', broker='pyamqp://guest@localhost//')
```

But the code below, can't specify the broker URL, maybe there should be an environment variable called `celery_broker` or something else, used to configure the broker URL.

https://github.com/novacode-nl/odoo-celery/blob/81fea36e943630f7fca3ac087ced89ffe3ff0df4/celery/odoo.py#L35

**Comment by bobslee** [comment]
Hi @ruter , @oadiazp 

By coincidence there's a PR (odoo 11.0) which addresses this, https://github.com/novacode-nl/odoo-celery/pull/40

Please checkout the the changeset (code).
We still need to document and merge.

**Comment by bobslee** [comment]
@ruter , @oadiazp see also the PR #41 for Odoo v13.
I close this issue now.
