### ISSUE TITLE
Improve README file

### ISSUE THREAD

**Issue by ovnicraft** [novacode-nl/odoo-celery#44]
I consider we can improve the README the file to describe main topics:
* How to install
* How to use
* Recommended lectures about Celery.

**Comment by ovnicraft** [comment]
@bobslee what do you think about this?

**Comment by bobslee** [comment]
For me ok, go ahead with a PR.
I'm not really active with the module for a while.

Did you already checkout out: https://apps.odoo.com/apps/modules/14.0/celery/
Which is rendered by the HTML https://github.com/novacode-nl/odoo-celery/blob/14.0/celery/static/description/index.html
