### ISSUE TITLE
A question about usage pattern

### ISSUE THREAD

**Issue by burinov** [novacode-nl/odoo-celery#5]
Hi Bob!

I am looking for a queue module for my odoo 11 installation. I want to put calls to external API to the queue.

Please tell me, where your odoo-celery module is designed for this type of use?

Would be great to see an example of putting some data to celery for external processing.

Best regards,
Max

**Comment by bobslee** [comment]
Hi @burinov 

I'm sorry for my late answer.

Yes indeed, this (celery) module is designed for your use case.

An example is implemented in the model of the module: https://github.com/novacode-nl/odoo-celery/tree/11.0/celery_example
See the method call: `self.env["celery.task"].call_task("celery.example", "queue_countdown_example_line", example_id=self.id, celery=celery)`

Let me know, in case you have any questions/remarks  :-)
Bob

**Comment by burinov** [comment]
Hi @bobslee !

Thank you for your reply! Celery works great for my odoo installation.
Thank you for your reply!
