### ISSUE TITLE
TypeError: value is undefined

### ISSUE THREAD

**Issue by zohaibrehman** [novacode-nl/odoo-celery#7]
I am using celery_example module but when i try to create add line it shows this error

**Comment by bobslee** [comment]
Please add the error and any info needed to analyse.

**Comment by zohaibrehman** [comment]
Error:
TypeError: value is undefined

http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:962
Traceback:
formatDateTime@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:962:57
_renderBodyCell@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1583:137
_renderRow/$cells<@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1601:127
_.collect@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:13:270
_renderRow@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1601:80
_renderRow@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1546:59
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3819:368
_.collect@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:13:270
_renderRows@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1602:83
_renderRows@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1547:48
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3819:368
_renderBody@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1577:52
_renderBody@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1545:364
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3819:368
_renderView@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1603:499
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
_renderView@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1548:67
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3819:368
_render@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1297:173
_render@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1545:295
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3819:613
updateState@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1081:510
updateState@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1570:1452
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
_render@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1034:19
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
reset@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:892:348
reset@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1033:8
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
reset@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1041:1320
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
confirmChange/<@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1283:187
_.forEach@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:12:558
confirmChange@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1283:33
confirmChange@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1330:845
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
confirmChange@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:2265:8
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3819:368
_confirmChange@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1271:2211
_applyChanges/<@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1303:711
then/</</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:678
fire@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:796:281
add@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:797:467
then/</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:649
each@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:625:758
then/<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:553
Deferred@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:803:189
then@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:518
_applyChanges@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1303:557
_applyChanges/<@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1271:1458
exec/<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:4009:295
then/</</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:678
fire@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:796:281
add@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:797:467
then/</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:649
each@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:625:758
then/<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:553
Deferred@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:803:189
then@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:518
exec@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:4009:257
_applyChanges@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1271:1424
OdooClass.extend/</prototype[name]</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3816:485
_onFieldChanged@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1303:922
_onFieldChanged@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1278:1
proxy/<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3917:8
trigger@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3915:166
_trigger_up@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3921:340
_trigger_up@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3921:442
_trigger_up@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3921:442
trigger_up@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:3921:275
_setValue@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:895:62
on_saved@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1041:2390
_save/<@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1321:370
then/</</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:678
fire@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:796:281
add@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:797:467
then/</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:649
each@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:625:758
then/<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:553
Deferred@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:803:189
then@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:802:518
_save@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1321:282
click@http://localhost:1091/web/content/556-2b43e53/web.assets_backend.js:1316:1905
set_buttons/</<@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:4049:404
dispatch@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:892:378
add/elemData.handle@http://localhost:1091/web/content/532-9e212ce/web.assets_common.js:865:151

**Comment by zohaibrehman** [comment]
I ve added the error

**Comment by zohaibrehman** [comment]
Have you received my recent update regarding error?

**Comment by bobslee** [comment]
Hi @zohaibrehman 

I just tested with Odoo 11 and 12 versions of those modules (celery, celery_example).
It just works on my side.

**Maybe the following led to confusion, because it's still not documented (my debt).**

On the "Celery Example" screen you see 3 buttons, whereby each button dispatches to a different worker which has a queue name configured. For more Celery worker options, like concurrency, see the Celery (project) documentation.

Start the workers like following:

**Task queue=default** (action button)
`celery -A odoo worker --loglevel=info`

**Task queue=high** (action button)
`celery -A odoo worker -l info -Q high`

**Task queue=low** (action button)
`celery -A odoo worker -l info -Q low`

Incase this won't help you...

**Please provide more info:**

- Odoo log (the part where an error occur)
- Celery worker log/output
- Operating system (version)
- Odoo version (core and the celery modules)
- Odoo Community or Enterprise?
- Did you run all installation and confguration steps mentoined on https://www.odoo.com/apps/modules/12.0/celery/ (11.0 and 12.0 are the same in this matter).

**Comment by bobslee** [comment]
Hi @zohaibrehman is the issue still valid ?

**Comment by zohaibrehman** [comment]
Yes I was still facing and then did nt touch after that

**Comment by bobslee** [comment]
Ok, in case you need support...
Could you please provide me the info I asked?

**Comment by zohaibrehman** [comment]
its giving javascrit error

**Comment by bobslee** [comment]
That's a bummer. It just works on my side, my customers  and a lot of other users/developers.

Could you just test with these modules **celery** and **celery_example**?
Without any custom modules please.

Also see my explanation and request for more info in my comment: https://github.com/novacode-nl/odoo-celery/issues/7#issuecomment-486542425

**Comment by zohaibrehman** [comment]
Actually I also lost my server access so I can't show anything right now.
As soon I will get back access I will inform you wt the issue is coming. I
ve also shown screen shot on email and detailed error on git

**Comment by bobslee** [comment]
Ok. I hope you'll come back with more detailed info.
Until then I close this issue, because the circumstances I asked for ain't clear to me yet.
