### ISSUE TITLE
Store and provide exception message (new field)

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-celery#8]
In case an exception occurs, the trace is already stored into the field `exc_info`.
It's maybe be beneficial to store only the message too - so one could filter or report about the type of errors (task failures) which occur after a while.

**To implement:**
- Add field `exc_message` in model `celery.task`
- Add field to views: `tree`, `form` and `search` (autocomplet, groupby?)

**Comment by KirylSudnikovich** [comment]
@bobslee Is the task still relevant? I can implement this

**Comment by bobslee** [comment]
@0311snitch This is a nice to have.
If you need this, of course you could implement.
